"""Export a trained checkpoint into a browser-loadable bundle (web/bundle.js).

    uv run python export_web.py [checkpoint.pt]
    uv run python export_web.py checkpoint_dmg.pt --out web/bundle_dmg.js \
        --var BUNDLE_DMG            # a second model, side by side in the demo

Writes a JS file:  const BUNDLE = { n, channels, pos, csr_off, csr_src,
                                    w1, b1, w2, seed, target, alive_alpha_idx }
Pure JS reads this -- no server, no build step, just open web/index.html.
"""
import argparse, json, os
import numpy as np, torch

p = argparse.ArgumentParser()
p.add_argument("checkpoint", nargs="?", default="checkpoint.pt")
p.add_argument("--out", default="web/bundle.js")
p.add_argument("--var", default="BUNDLE", help="the const the JS file declares")
a = p.parse_args()

ckpt = torch.load(a.checkpoint, weights_only=False)
pos = np.asarray(ckpt["pos"], dtype=np.float32)          # (N,2)
edges = ckpt["edges"].numpy()                            # (2,E)
C = ckpt["channels"]
tgt = np.asarray(ckpt["target"], dtype=np.float32)       # (N,4)

# ---- build CSR adjacency sorted by destination node (for mean aggregation) ----
dst = np.argsort(edges[1])
src_by_dst = edges[0][dst]
deg = np.bincount(edges[1], minlength=pos.shape[0])
off = np.concatenate([[0], np.cumsum(deg)]).astype(np.int32)

# ---- MLP weights: net = Linear(3C,128) -> ReLU -> Linear(128,C, bias=False) ----
model_w = ckpt["model"]
w1 = model_w["net.0.weight"].cpu().numpy().astype(np.float32)  # (128, 3C)
b1 = model_w["net.0.bias"].cpu().numpy().astype(np.float32)    # (128,)
w2 = model_w["net.2.weight"].cpu().numpy().astype(np.float32)  # (C, 128)

# seed = node nearest the heart center (works for any graph)
seed = int(np.argmin(((pos - 0.5) ** 2).sum(1)))

bundle = {
    "n": int(pos.shape[0]),
    "channels": int(C),
    "alive_alpha_idx": 3,
    "pos": pos.reshape(-1).tolist(),
    "csr_off": off.tolist(),
    "csr_src": src_by_dst.astype(np.int32).tolist(),
    "w1": w1.reshape(-1).tolist(),
    "b1": b1.tolist(),
    "w2": w2.reshape(-1).tolist(),
    "target": tgt.reshape(-1).tolist(),
    "seed": seed,
}
os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
with open(a.out, "w") as f:
    f.write(f"// auto-generated by export_web.py -- do not edit\nconst {a.var} = ")
    f.write(json.dumps(bundle))
    f.write(";\n")
print(f"wrote {a.out}  ({os.path.getsize(a.out)//1024} KB, {bundle['n']} nodes, "
      f"{len(bundle['csr_src'])} directed edges, from {a.checkpoint})")
