"""UMAP 'cell type' view for a trained Graph NCA.

Rolls the model out from the seed, embeds the hidden channels of every alive
node (all timesteps together, so the map is comparable across time) with UMAP,
quantizes the states into a palette of centroids, and writes:

  web/artifacts/<name>-umap.js   export default {k, hdim, centroids, colors, ...}
  docs/media/umap.png            inspection scatter: by time, and by palette color

    uv run python scripts/render/umap_states.py --ckpt runs/checkpoint_bunny_pc.pt
"""
import argparse
import json
import os

os.environ.pop("MPLBACKEND", None)
import numpy as np
import torch
from sklearn.cluster import KMeans

from gnca import alive_mask, load_checkpoint, seed_state

p = argparse.ArgumentParser()
p.add_argument("--ckpt", default="runs/checkpoint.pt")
p.add_argument("--steps", type=int, default=120)
p.add_argument("--every", type=int, default=2, help="record states every n steps")
p.add_argument("--k", type=int, default=48, help="palette size (centroids)")
p.add_argument("--max-points", type=int, default=60000, help="UMAP subsample cap")
p.add_argument("--out-js", default="web/artifacts/bunny-umap.js")
p.add_argument("--out-png", default="docs/media/umap.png")
args = p.parse_args()

device = "mps" if torch.backends.mps.is_available() else "cpu"
ck = load_checkpoint(args.ckpt, device)
edges, model = ck.edges, ck.model
C, N = ck.channels, ck.n
HDIM = C - 4                                    # hidden channels only

# ---- collect hidden states over a growth rollout ----
x = seed_state(1, N, C, device, ck.center)[0]
snaps, times = [], []
with torch.no_grad():
    for t in range(args.steps):
        if t % args.every == 0:
            alive = x[:, 3] > 0.1
            if alive.sum() > 10:
                snaps.append(x[alive, 4:C].cpu().numpy())
                times.append(np.full(int(alive.sum()), t))
        x = model(x, edges) * alive_mask(x, edges)
H = np.vstack(snaps).astype(np.float32)
T = np.concatenate(times)
if len(H) > args.max_points:                    # UMAP slows past ~100k points
    keep = np.random.default_rng(0).choice(len(H), args.max_points, replace=False)
    H, T = H[keep], T[keep]
print(f"{len(H)} state samples ({HDIM}-d hidden) from {args.steps} steps")

# ---- embed: one 2-d map for all timesteps ----
import umap

emb = umap.UMAP(n_neighbors=15, min_dist=0.1, random_state=0).fit_transform(H)

# ---- quantize: palette of centroids in hidden space, colored by map position ----
km = KMeans(n_clusters=args.k, n_init=4, random_state=0).fit(H)
cent2d = np.stack([emb[km.labels_ == k].mean(0) for k in range(args.k)])
c = cent2d - cent2d.mean(0)
ang = (np.arctan2(c[:, 1], c[:, 0]) + np.pi) / (2 * np.pi)        # hue
rad = np.linalg.norm(c, axis=1)
rad = rad / rad.max()
from matplotlib.colors import hsv_to_rgb

colors = hsv_to_rgb(np.stack([ang, 0.45 + 0.55 * rad, np.full(args.k, 0.95)], 1))

# normalize the map to [-1, 1] (single scale, aspect preserved) for the demo
span = np.abs(emb).max()
emb_n = emb / span * 0.95
cent2d_n = cent2d / span * 0.95
sub = np.random.default_rng(0).choice(len(emb_n), min(8000, len(emb_n)), replace=False)

payload = {"k": int(args.k), "hdim": int(HDIM),
           "centroids": km.cluster_centers_.astype(np.float32).reshape(-1).tolist(),
           "colors": colors.astype(np.float32).reshape(-1).tolist(),
           "cent2d": np.round(cent2d_n, 4).reshape(-1).tolist(),
           "pts": np.round(emb_n[sub], 3).reshape(-1).tolist()}
os.makedirs(os.path.dirname(args.out_js) or ".", exist_ok=True)
with open(args.out_js, "w") as f:
    f.write("// auto-generated by umap_states.py -- do not edit\nexport default ")
    f.write(json.dumps(payload))
    f.write(";\n")
print(f"wrote {args.out_js} ({os.path.getsize(args.out_js)//1024} KB, "
      f"{args.k} centroids x {HDIM} hidden dims)")

# ---- inspection scatter ----
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, (a1, a2) = plt.subplots(1, 2, figsize=(11, 5), dpi=110)
s1 = a1.scatter(emb[:, 0], emb[:, 1], c=T, cmap="viridis", s=2, linewidths=0)
a1.set_title("colored by rollout time")
fig.colorbar(s1, ax=a1, label="t")
a2.scatter(emb[:, 0], emb[:, 1], c=colors[km.labels_], s=2, linewidths=0)
a2.scatter(cent2d[:, 0], cent2d[:, 1], c=colors, s=40, edgecolors="white",
           linewidths=0.5, zorder=3)
a2.set_title(f"colored by palette ({args.k} cell types)")
for a in (a1, a2):
    a.set_xticks([]); a.set_yticks([])
fig.tight_layout()
os.makedirs(os.path.dirname(args.out_png) or ".", exist_ok=True)
fig.savefig(args.out_png)
print(f"saved {args.out_png}")
