"""Export a trained checkpoint into a browser-loadable bundle (web/bundle.js).

    uv run python scripts/export_web.py [runs/checkpoint.pt]
    uv run python scripts/export_web.py runs/checkpoint_dmg.pt \
        --out web/bundle_dmg.js --var BUNDLE_DMG   # a second model in the demo

Writes a JS file:  const BUNDLE = { n, channels, pos, csr_off, csr_src,
                                    w1, b1, w2, seed, target, alive_alpha_idx }
Pure JS reads this -- no server, no build step, just open web/index.html.
"""
import argparse
import json
import os

import numpy as np
import torch

p = argparse.ArgumentParser()
p.add_argument("checkpoint", nargs="?", default="runs/checkpoint.pt")
p.add_argument("--out", default="web/bundle.js")
p.add_argument("--var", default="BUNDLE", help="the const the JS file declares")
a = p.parse_args()

ckpt = torch.load(a.checkpoint, weights_only=False)
pos = np.asarray(ckpt["pos"], dtype=np.float32)          # (N, 2) or (N, 3)
if pos.ndim != 2 or pos.shape[1] not in (2, 3):
    raise SystemExit(f"expected pos (N,2|3), got {pos.shape}")
dim = int(pos.shape[1])
edges = ckpt["edges"]
edges = edges.numpy() if torch.is_tensor(edges) else np.asarray(edges)  # (2,E)
C = ckpt["channels"]
tgt = np.asarray(ckpt["target"], dtype=np.float32)       # (N,4)

# ---- build CSR adjacency sorted by destination node (for mean aggregation) ----
dst = np.argsort(edges[1])
src_by_dst = edges[0][dst]
deg = np.bincount(edges[1], minlength=pos.shape[0])
off = np.concatenate([[0], np.cumsum(deg)]).astype(np.int32)

# ---- MLP weights: net = Linear(3C,128) -> ReLU -> Linear(128,C, bias=False) ----
model_w = ckpt["model"]
w1t = model_w["net.0.weight"]
if w1t.shape[1] != 3 * C:
    raise SystemExit(
        f"checkpoint percept is {w1t.shape[1]} inputs wide, but the web demo "
        f"implements the pre-degree-feature rule (3C={3 * C}, no gate). Export "
        "a pre-#17 checkpoint, or teach demo.js the degree feature + gate first."
    )
w1 = w1t.cpu().numpy().astype(np.float32)                      # (128, 3C)
b1 = model_w["net.0.bias"].cpu().numpy().astype(np.float32)    # (128,)
w2 = model_w["net.2.weight"].cpu().numpy().astype(np.float32)  # (C, 128)

# prefer the seed node training used; fall back to nearest cube centre
if "center" in ckpt:
    seed = int(ckpt["center"])
else:
    seed = int(np.argmin(((pos - 0.5) ** 2).sum(1)))

bundle = {
    "n": int(pos.shape[0]),
    "channels": int(C),
    "dim": dim,
    "alive_alpha_idx": 3,
    "pos": pos.reshape(-1).tolist(),
    "csr_off": off.tolist(),
    "csr_src": src_by_dst.astype(np.int32).tolist(),
    "w1": w1.reshape(-1).tolist(),
    "b1": b1.tolist(),
    "w2": w2.reshape(-1).tolist(),
    "target": tgt.reshape(-1).tolist(),
    "seed": seed,
    "target_name": ckpt.get("target_name", ""),
}
os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
with open(a.out, "w") as f:
    f.write(f"// auto-generated by export_web.py -- do not edit\nconst {a.var} = ")
    f.write(json.dumps(bundle))
    f.write(";\n")
print(f"wrote {a.out}  ({os.path.getsize(a.out)//1024} KB, {bundle['n']} nodes, "
      f"dim={dim}, {len(bundle['csr_src'])} directed edges, from {a.checkpoint})")
